# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: de
title: Zukunft@Stadtwerke Flensburg
email: flensburg.fossilfrei@posteo.de
description: >- # this means to ignore newlines until "baseurl:"
  Die Stadtwerke Flensburg suchen nach einer neuen Leitung der Geschäftsführung.<br>
  Sind Sie der Mensch, der die umfassende Transformation eines mittelgroßen
  kommunalen Konzerns zu einem führenden Dienstleister der erneuerbaren Energien einleiten wird
  - oder kennen eine Person, der Sie dies zutrauen? Dann lesen Sie weiter...
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/stadtwerk-mit-zukunft" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: null   # workaround for jekyll issue #7478 (caused by github-pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:        # set default open graph preview image (i.e. for facebook/twitter) as per https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
      path: ""
    values:
      image: /assets/images/swfl/home.jpg

sass:
  style: compressed

exclude:
  - _config_production.yml
  - vendor
  - README.md
  - LICENSE
  - Gemfile*

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
